#define SECRET_WIFI_SSID "YOUR_REAL_WIFI_NAME"
#define SECRET_WIFI_PASS "YOUR_REAL_WIFI_PASSWORD"

#define SECRET_MQTT_URL "YOUR_REAL_CLUSTER_URL.s1.eu.hivemq.cloud"
#define SECRET_MQTT_USER "YOUR_REAL_USERNAME"
#define SECRET_MQTT_PASS "YOUR_REAL_PASSWORD"